### ISSUE TITLE
Request: Add textbox to the actions field options

### ISSUE THREAD

**Issue by royberris** [Mulliman/xStatic-for-Umbraco#26]
Hi,

I have a feature request for the action parameters. This is a single line textfield right now but it would be nice if we could have a textbox which supports multiple lines. I want to write a post action that adds a `_headers` file to the output for Netlify but right now I have to do this hardcoded because the input from the CMS does not support multiple lines.

I am using it so the rss index file returns with the right content type for browsers to understand.

![image](https://github.com/Mulliman/xStatic-for-Umbraco/assets/25608596/7bc4fdb4-08a7-47fa-9068-e470c8dd8b82)

Would like to contribute above action to the Netlify package because I think it will be useful. But of course above version is not enough for the package because it is static.

**Comment by Mulliman** [comment]
Hey, to do this nicely I will need to make a breaking change and I would also need to roll it out to the other forms.

It's not really something I considered in the original, and despite having a hack in there for password fields it's a pretty rubbish way of doing it.

If you want to quickly enable this before I can do this properly you can change the following file to use a textarea rather than an input

`\App_Plugins\xStatic\fields\ConfigurableTypeField.html`

Next major version I'll try and rework this so we can have more input types.

**Comment by Mulliman** [comment]
There is now far better support for being able to do this in xStatic 14.
