### ISSUE TITLE
Question: Is it possible to handel 301/302 redirects

### ISSUE THREAD

**Issue by webmonger** [Mulliman/xStatic-for-Umbraco#7]
I'm thinking of using xStatic for some sites that have been live for some period of time. If we were to do so we would require support for some legacy URLs for SEO and other activities.

Is this possible or would much of that be lost when generating the site statically?

**Comment by Mulliman** [comment]
Hey.

Yes it is possible but it depends on where you intend to host it.
The redirects will need to be set up specifically for the edge server / cdn / host rather than generically in Umbraco.

This is how you could do it with Netlify, which is the service I'd most often recommend to use with xStatic:

https://docs.netlify.com/routing/redirects/

- Create a "_redirects" file in your umbraco site root directory.
- Fill this file in with your redirect(s), e.g. `/news              /blog`
- Add this file to the 'Asset Paths' field in xStatic for the site in question to ensure it gets built and deployed.
- Build and deploy from the xStatic dashboard.

The redirects should then work, but this isn't something I've done yet in real life. It would be interesting to see if it works for files without an extension.

If there is an issue with that file, you can use the 'netlify.toml' way to define them instead; I can't think of any issues this approach would cause.

**Comment by webmonger** [comment]
@Mulliman Thanks for the detail very helpful, I'm thinking of writing a Deploy mechanism for Azure Blob storage so it migth be logical at the same time to add some integrations with either Azure CDN or Azure FrootDoor depending on which support the most flexible functionality for this.

Great package by thet way 👍

**Comment by Mulliman** [comment]
If you have any questions about writing the deployer for Blob storage let me know, I've been doing a bit of work on a WebDeploy version so I could deploy to Azure Web Apps which I may put out once I can get it working on non Azure instances.
